Ajdust open_tablet_view method to 16.0
Mint-System/Odoo-Apps-Manufacture pull request #10
Opened 2024-10-15 11:16 UTC by laszlokr

2024-10-16 11:12 UTC, janikvonrotz requested changes

2024-10-16 11:12 UTC, janikvonrotz commented on mrp_workorder_disable_autostart/models/mrp_workorder.py
> +            action["context"] = {
This overwrites the entire context.

Try `action["context"]["from_production_order"] = `

2024-10-16 14:45 UTC, janikvonrotz commented on mrp_workorder_disable_autostart/models/mrp_workorder.py
> +            if not isinstance(action.get("context"), dict):
Context is always a dict. What is the goal of this check?

2024-10-17 06:50 UTC, laszlokr commented on mrp_workorder_disable_autostart/models/mrp_workorder.py
> +            if not isinstance(action.get("context"), dict):
Without this check there is an error:
```
models/mrp_workorder.py", line 26, in open_tablet_view
    action["context"]["active_id"] = self.id
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'str' object does not support item assignment
```

2024-10-17 07:09 UTC, janikvonrotz commented on mrp_workorder_disable_autostart/models/mrp_workorder.py
> +            if not isinstance(action.get("context"), dict):
```python
# Create and return action as defined in open_tablet_view
     action = self.env["ir.actions.actions"]._for_xml_id("mrp_workorder.tablet_client_action")
        action['target'] = 'fullscreen'
        action['res_id'] = self.id
        action['context'] = {
            'active_id': self.id,
            'from_production_order': self.env.context.get('from_production_order'),
            'from_manufacturing_order': self.env.context.get('from_manufacturing_order')
        }
        return action
```

2024-10-17 13:31 UTC, janikvonrotz approved these changes

2024-10-18 07:26 UTC, merged